yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('project/', views.AboutProjectView.as_view(), name='project'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'posts.views.page_not_found'  # noqa
handler500 = 'posts.views.server_error'  # noqa

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

yatube/templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="post card my-4">
    <form method="post" action="{% url 'add_comment' post.author.username post.id %}" >
      {% csrf_token %}
      <h5>Добавить комментарий:</h5>
      <!-- <div class="card-body" > -->
        <div class="form-group">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="button large">Отправить</button>
      <!-- </div> -->
    </form>
  </div>
{% endif %}

<!-- Комментарии -->
{% load tz %}

{% for item in comments %}
  <div class="post media card mb-4">
    <div class="media-body card-body">
      <h5 class="mt-0">
        <a href="{% url 'profile' item.author.username %}" name="comment_{{ item.id }}">{{ item.author.username }}</a>, <time class="published" style="text-transform: lowercase">{{ item.created|localtime }}</time>
      </h5>
      <p>{{ item.text|linebreaksbr }}</p>
    </div>
  </div>
{% endfor %}

yatube/templates/includes/footer.html
<section id="footer">
    <p class="copyright">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
</section>

yatube/templates/includes/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/includes/nav.html
{% load custom_tags %}
<header id="header">
    <h1><a href="{% url 'index' %}">Yatube</a></h1>
    <nav class="links">
        {% if user.is_authenticated %}        
        <ul>
            <li><h1><a href="{% url 'profile' user.username %}">Ваш профиль: {{ user.username }}</a></h1></li>                       
            <li><a href="{% url 'new_post' %}">Новая запись</a></li>
            <li><a href="{% url 'index' %}">Главная</a></li>
            <li><a href="{% url 'follow_index' %}">Подписки</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'login' %}">Войти</a></li>
            <li><a href="{% url 'signup' %}">Регистрация</a></li>
        </ul>
        {% endif %}
    </nav>
    <nav class="main">
        <ul>
            <li class="menu">
                <a class="fa-bars" href="#menu">Menu</a>
                
            </li>
        </ul>
    </nav>

</header>

<!-- Menu -->

<section id="menu">
    {% if user.is_authenticated %}

    <section>
        <ul class="actions stacked">
            <li><a href="{% url 'profile' user.username %}" class="button large fit">Профиль</a></li>
            <li><a href="{% url 'password_change' %}"class="button large fit">Изменить пароль</a></li> 
            <li><a href="{% url 'logout' %}" class="button large fit">Выйти</a></li>            
        </ul>
    </section>

    {% else %}
    <section>
        <ul class="actions stacked">
            <li><a href="{% url 'login' %}" class="button large fit">Вход</a></li>
            <li><a href="{% url 'signup' %}" class="button large fit">Регистрация</a></li>
        </ul>
    </section>
    {% endif %}
</section>

yatube/templates/includes/paginator.html
{% if page.has_other_pages %}
  <nav>
    <ul class="actions pagination">
      {% if page.has_previous %}
        <li><a class="button large previous" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a></li>
      {% else %}
        <li><a class="disabled button large previous">&laquo; Предыдущая</a></li>
      {% endif %}

      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li style="font-family: Source Sans Pro, Helvetica, sans-serif; font-size: 0.7em; font-weight: 700; color: rgba(160, 160, 160, 0.3); margin: 1.5em 1em;">
            <span >{{ i }}</span>
          </li>
        {% else %}
          <li style="font-family: Source Sans Pro, Helvetica, sans-serif; font-size: 0.7em; font-weight: 700; margin-top: 1.5em">
            <a href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page.has_next %}
        <li><a class="button large next" href="?page={{ page.next_page_number }}">Следующая &raquo;</a></li>
      {% else %}
        <li><span class="disabled button large next">Следующая &raquo;</span></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post_item.html
<article class="post">
  <header>
    <div class="title">
      <h2><a href="single.html">{{ post.title }}</a></h2>
      <p>{{ post.subtitle }}</p>
    </div>
    <div class="meta" style="text-align: left">
        <time class="published">{{ post.pub_date }}</time>
        <a href="{% url 'profile' post.author.username %}" class="author" style="text-align: left"><span class="name">@{{ post.author }}</span></a>
        {% if post.group %}
        <a href="{% url 'group' post.group.slug %}" class="author" style="text-align: left"><span class="name">#{{ post.group.title }}</span></a>
        {% endif %}
    
    </div>
  </header>

  <!-- Отображение картинки -->
  {% load thumbnail %}
  <a href="{% url 'post' post.author.username post.id %}" class="image featured">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %} 
  </a>  

  <p>{{ post.text|linebreaksbr }}</p>

  <footer>
    {% if not comments %}
    <ul class="actions">
      <li><a href="{% url 'post' post.author.username post.id %}" class="button large">Открыть</a></li>
    </ul>
    {% endif %}
    <ul class="stats">
      {% if user == post.author %}
      <li><a href="{% url 'post_edit' post.author.username post.id %}">Редактировать</a></li>
      {% endif %}
      <li><a href="{% url 'like' post.author.username post.id %}" class="icon solid fa-heart">{{ post.likes.count }}</a></li>
      <li><a href="{% url 'post' post.author.username post.id %}" class="icon solid fa-comment">{{ post.comments.count }}</a></li>
    </ul>
  </footer>

  
</article>

yatube/templates/includes/sidebar.html
<section id="sidebar">
    <!-- Intro -->
    {% load static %}
    {% if author %}
      <section id="intro">
        <a href="#" class="logo"><img src="{% static 'images/logo.jpg' %}" alt="" /></a>
        <header>
            <h2><a href="{% url 'profile' author.username %}"> {{ author.get_full_name|default:"Админ" }} </a></h2>
            <h3><a href="{% url 'profile' author.username %}">@{{ author.username }}</a></h3>
            <p>
                Подписчиков: {{ followed_by }} <br />
                Подписан: {{ follows }}
            </p>
            <p>
                Записей: {{ posts_count }}
            </p>
        </header>
        {% if author != request.user and not post%}
            {% if following %}
                <a class="button large" href="{% url 'profile_unfollow' author %}" role="button">
                Отписаться
                </a>
            {% else %}
                <a class="button large" href="{% url 'profile_follow' author %}" role="button">
                Подписаться
                </a>
            {% endif %}
        {% endif %}
      </section>
    {% else %}
        {% if group %}
        <section id="intro">
            <a href="{% url 'index' %}" class="logo"><img src="{% static 'images/logo.jpg' %}" alt="" /></a>
            <header>
                <h2>#{{ group.title }}</h2>
                <h3>{{ group.description }}</h3>
                <p>Записи сообщества</p>
            </header>
        </section>
        {% else %}
        <section id="intro">
            <a href="{% url 'index' %}" class="logo"><img src="{% static 'images/logo.jpg' %}" alt="" /></a>
            <header>
                <h2><a href="{% url 'index' %}">Yatube</a></h2>
                <p>The Last Social Media You'll Ever Need</p>
            </header>
        </section>
        {% endif %}
    {% endif %}
    <!-- <section>
        <div class="mini-posts">            
            <article class="mini-post">
                <header>
                    <h3><a href="{% url 'index' %}">Все авторы</a></h3>
                    
                </header>
            </article>            
        </div>
        <div class="mini-posts">            
            <article class="mini-post">
                <header>
                    <h3><a href="{% url 'follow_index' %}">Подписки</a></h3>
                    
                </header>
            </article>            
        </div>
    </section> -->
    <section>
        <ul class="posts">
            <li>
                <article>
                    <header>
                        <h3><a href="{% url 'about:project' %}">О проекте</a></h3>
                        <!-- <time class="published" datetime="2015-10-20">October 20, 2015</time> -->
                    </header>
                    <a href="{% url 'about:tech' %}" class="image"><img src="{% static 'images/pic08.jpg' %}" alt="" /></a>
                </article>
            </li>
            <li>
                <article>
                    <header>
                        <h3><a href="{% url 'about:author' %}">Об авторе</a></h3>
                        <!-- <time class="published" datetime="2015-10-20">October 20, 2015</time> -->
                    </header>
                    <a href="{% url 'about:author' %}" class="image"><img src="{% static 'images/pic09.jpg' %}" alt="" /></a>
                </article>
            </li>
            <!-- <li>
                <article>
                    <header>
                        <h3><a href="{% url 'about:tech' %}">Технологии</a></h3>
                        <time class="published" datetime="2015-10-20">October 20, 2015</time>
                    </header>
                    <a href="{% url 'about:tech' %}" class="image"><img src="{% static 'images/pic10.jpg' %}" alt="" /></a>
                </article>
            </li> -->
            
        </ul>
    </section>

    <!-- About -->
    <!-- <section class="blurb">
        <h2>О проекте</h2>
        <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl.</p>
        <ul class="actions">
            <li><a href="{% url 'about:author' %}" class="button">Learn More</a></li>
        </ul>
    </section>
    <section class="blurb">
        <h2>Об авторе</h2>
        <p>Привет! Меня зовут Екатерина</p>
        <ul class="actions">
            <li><a href="{% url 'about:author' %}" class="button">Learn More</a></li>
        </ul>
    </section> -->
    <section class="blurb">
        <h2>Технологии </h2>
        <p>Разработано на Django с использованием SQLite. <br>
            Оформление: <a href="http://html5up.net">HTML5 UP</a>.</p>
        <ul class="actions">
            <li><a href="{% url 'about:tech' %}" class="button">Подробнее</a></li>
        </ul>
    </section>

    {% include 'includes/footer.html' %}
</section>

yatube/templates/includes/user_card.html
<div class="card">
    <div class="card-body">
    <div class="h2">
        {{ author.get_full_name|default:"Админ" }}
    </div>
    <div class="h3 text-muted">
        @{{ author.username }}
    </div>
    </div>
    <ul class="list-group list-group-flush">
    <li class="list-group-item">
        <div class="h6 text-muted">
        Подписчиков: {{ followed_by }} <br />
        Подписан: {{ follows }}
        </div>
    </li>
    <li class="list-group-item">
        <div class="h6 text-muted">
        Записей: {{ posts_count }}
        </div>
    </li>
    </ul>
</div>